# syntax=docker/dockerfile:1.4

# Create image based on the official Node image from dockerhub
FROM node:lts-bookworm-slim AS development

# Create app directory
WORKDIR /usr/src/app

# Copy dependency definitions
COPY package.json /usr/src/app
COPY package-lock.json /usr/src/app

# Install dependecies
#RUN npm set progress=false \
#    && npm config set depth 0 \
#    && npm i install
RUN npm ci

# Get all the code needed to run the app
COPY . /usr/src/app

# Expose the port the app runs in
EXPOSE 5173

# Serve the app
CMD ["npm", "run", "dev"]

# COPY . .
RUN npm run build

# Expose the port the app runs in
# FROM nginx:alpine

# Copy built static files from build stage
# COPY --from=build /usr/src/app/dist /usr/share/nginx/html

# Copy custom Nginx config
# COPY nginx.conf /etc/nginx/conf.d/default.conf

# EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]