services:
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 5173:5173
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - react-express-pribex
    depends_on:
      - backend

  backend:
    build:
      context: backend
      target: development
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - react-express-pribex
    restart: unless-stopped
    ports: 
      - 3000:3000
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./backend/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - react-express-pribex

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    depends_on:
      - prometheus
    networks:
      - react-express-pribex
  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - react-express-pribex
    command: ["redis-server", "--appendonly", "yes"]
networks:
  react-express-pribex:
    name: react-express-pribex
    driver: bridge
volumes:
  redis-data:
    driver: local