services:
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 5173:5173
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    networks:
      - react-express-pribex
    depends_on:
      - backend

  backend:
    build:
      context: backend
      target: development
    environment:
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - react-express-pribex
    restart: unless-stopped
    ports: 
      - 3000:3000
networks:
  react-express-pribex:
    name: react-express-pribex
    driver: bridge