# syntax=docker/dockerfile:1.4

FROM node:lts-bookworm-slim AS development

# Create app directory
WORKDIR /usr/src/app

COPY package.json /usr/src/app/package.json
COPY package-lock.json /usr/src/app/package-lock.json
RUN npm ci

COPY . /usr/src/app

ENV PORT=3000
ENV CORS_ORIGIN=http://localhost:5173

EXPOSE $PORT

CMD [ "npm", "run", "dev" ]