# syntax=docker/dockerfile:1.4

FROM node:lts-bookworm-slim AS development

# Create app directory
WORKDIR /usr/src/app

COPY package.json /usr/src/app/package.json
COPY package-lock.json /usr/src/app/package-lock.json
RUN npm ci

COPY . /usr/src/app

ENV PORT=3000
ENV MONGO_URI=mongodb+srv://<username>:<password>@mongoproject.y2aij.mongodb.net
ENV CORS_ORIGIN=http://localhost:5173

EXPOSE $PORT

CMD [ "npm", "run", "dev" ]

FROM development as dev-envs
RUN <<EOF
apt-get update
apt-get install -y --no-install-recommends git
EOF

RUN <<EOF
useradd -s /bin/bash -m vscode
groupadd docker
usermod -aG docker vscode
EOF
# install Docker tools (cli, buildx, compose)
COPY --from=gloursdocker/docker / /
CMD [ "npm", "run", "dev" ]
